add pinconfig and hal for gd32c10xxx
zephyrproject-rtos/hal_gigadevice pull request #13
Opened 2021-11-22 21:57 UTC by feilongfl

Hi!
this PR add support for `gd32c10xxx` device and old `gd32e103xx` device.

hal code from:
http://www.gd32mcu.com/cn/download/7?kw=GD32C1
-> GD32C10x Firmware Library  `V1.0.1`

I made some modifications to hal code with reference to https://github.com/zephyrproject-rtos/hal_gigadevice/pull/6

2021-11-30 09:17 UTC, gmarull requested changes

2021-11-30 09:17 UTC, gmarull commented on include/dt-bindings/pinctrl/gd32c103c(b-8)xx-pinctrl.h
> +#include "gd32c103xx-afio.h"
I can't see this file in this PR

2021-11-30 09:17 UTC, gmarull commented on gd32c10x/standard_peripheral/Source/gd32c10x_can.c
> +#define CAN_TIMEOUT                        ((uint32_t)0x0000FFFFU)      /*!< timeout value */
this definitions need to be public, see https://github.com/zephyrproject-rtos/hal_gigadevice/blob/main/gd32f4xx/standard_peripheral/include/gd32f4xx_can.h#L597

2021-11-30 21:56 UTC, nandojve requested changes
Hi @feilongfl .
You need review `dt-bindings: add pinctrl gd32c103xx generated headers` commit. There is mention to gd32c**4**03xx MCU.

This can only be merged after a board be build at main repository,

2024-12-19 12:59 UTC, gmarull commented
stale

2024-12-19 12:59 UTC, closed without merging